# -*- coding: utf-8 -*-
"""FruitSelector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wMpbbbCkTijVyWkQuTPSYBygNd4pXIZX
"""

from fastai import *

from fastai.vision import *

path = Path('drive/My Drive/Colab Notebooks/Fruits')

folder = 'trauben'
file = 'trauben.csv'

folder2 = 'banana'
file2 = 'banana.csv'

folder3 = 'apple'
file3 = 'apple.csv'

destApple = path/folder3
destApple.mkdir(parents=True, exist_ok=True)

destBanana = path/folder2
destBanana.mkdir(parents=True, exist_ok=True)

destTraube = path/folder
destTraube.mkdir(parents=True, exist_ok=True)

path.ls()

classes = ['apple','banana','trauben']

#download_images(path/file, destTraube, max_pics=40, max_workers=0)

#download_images(path/file2, destBanana, max_pics=40, max_workers=0)

#download_images(path/file3, destApple, max_pics=40, max_workers=0)

for c in classes:
    print(c)
    verify_images(path/c, delete=True, max_size=500)

np.random.seed(42)
data = ImageDataBunch.from_folder(path, train=".", valid_pct=0.2,
        ds_tfms=get_transforms(), size=40, num_workers=4).normalize(imagenet_stats)

data.classes

data.show_batch(rows=3, figsize=(7,8))

data.classes, data.c, len(data.train_ds), len(data.valid_ds)

learn = cnn_learner(data, models.resnet34, metrics=error_rate)

learn.fit_one_cycle(4)

learn.save('stage-1')

learn.unfreeze()

learn.lr_find()

learn.recorder.plot()

learn.fit_one_cycle(2, max_lr=slice(3e-5,3e-4))

learn.save('stage-2')

learn.load('stage-2');

interp = ClassificationInterpretation.from_learner(learn)

interp.plot_confusion_matrix()

#from fastai.widgets import *

#db = (ImageList.from_folder(path)
                   .split_none()
                   .label_from_folder()
                   .transform(get_transforms(), size=224)
                   .databunch()
     )

#learn_cln = cnn_learner(db, models.resnet34, metrics=error_rate)

#learn_cln.load('stage-2');

#ds, idxs = DatasetFormatter().from_toplosses(learn_cln)